config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'movie is already on the list' }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(%i[comment movie_id])
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1> Book mark page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1 class="banner">Create a movie list📽️🎬</h1>

<p class="mb-5"><%= link_to "+Add a movie list",  new_list_path(@list), class: "btn btn-success" %></p>
<div class="">
<% @lists.each do |list| %>
<ul>
  <li>
  <%= link_to list.name, list_path(list), class: "text-decoration-none" %>
  <%= link_to "❌delete ", list_path(list), data:{turbo_method: :delete}, class: "btn btn-light" %>
  </li>
  </ul>
<% end %>
</div>

app/views/lists/new.html.erb
<h1 class="mb-5">Add a new movie list</h1>
<div class="form-controll mb-5">
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
  <% end %>
  </div>

<%= link_to "Back to lists",  lists_path, class: "btn btn-secondary" %>

app/views/lists/show.html.erb
<h1><%= @list.name %>🎬</h1>

<div class="container">
<% @movies.each do |movie| %>
<div class=" container card mb-4">

  <p><%= image_tag movie.poster_url, width:200, height:200 %></p>
  <p><%= movie.title  %></p>
  <p>rating: <%= movie.rating %></p>
  <p> <%= Bookmark.find_by(movie_id: movie.id).comment %></p>
 </div>
<% end %>
</div>


<%= simple_form_for [@list, @bookmark ] do |f| %>
  <%= f.input :comment, placeholder: "Add a nice comment" %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-light" %>
<% end %>